class: "QnA"
description: "This is a schema for Query-Answer-Cited Document"
vectorizer: "text2vec-huggingface"
moduleConfig:
  text2vec-huggingface:
    model: "intfloat/e5-small-v2"
    options:
      waitForModel: True
  generative-openai:
    model: "gpt-3.5-turbo"
    options:
      waitForModel: True
properties:
- name: "cited_documents"
  dataType: ["Documents"]
- name: "question_id"
  dataType: ["number"]
  skip_vectorization: True
- name: "question"
  dataType: ["text"]
- name: "answer"
  dataType: ["text"]
